"""Tool definitions for market analysis agents."""

MARKET_TOOLS = [
    {
        "name": "get_market_quote",
        "description": "Get the current market quote (bid, ask, last price, volume) for a specific ticker symbol.",
        "input_schema": {
            "type": "object",
            "properties": {
                "ticker": {
                    "type": "string",
                    "description": "The ticker symbol (e.g., AAPL, SPY, BTC/USD)",
                }
            },
            "required": ["ticker"],
        },
    },
    {
        "name": "get_trading_signals",
        "description": "Get current trading signals generated by the strategy engine for a ticker. Returns signals with direction (long/short), strength (0-1), entry price, stop loss, and take profit.",
        "input_schema": {
            "type": "object",
            "properties": {
                "ticker": {
                    "type": "string",
                    "description": "The ticker symbol",
                },
                "timeframe": {
                    "type": "string",
                    "description": "Timeframe for analysis (1m, 5m, 15m, 1h, 4h, 1d)",
                    "enum": ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
                    "default": "1h",
                },
            },
            "required": ["ticker"],
        },
    },
    {
        "name": "get_market_overview",
        "description": "Get market overview including quotes for multiple tickers at once.",
        "input_schema": {
            "type": "object",
            "properties": {
                "tickers": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of ticker symbols to get quotes for",
                }
            },
            "required": ["tickers"],
        },
    },
]
