"""Abstract base Strategy class."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import numpy as np


@dataclass
class Candle:
    """Single OHLCV candle."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""

    signal_type: str  # entry, exit, scale_in, scale_out
    direction: str  # long, short
    strength: float  # 0.0 - 1.0
    price: float
    stop_loss: float | None = None
    take_profit: float | None = None
    timeframe: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def risk_reward_ratio(self) -> float | None:
        if self.stop_loss is None or self.take_profit is None:
            return None
        risk = abs(self.price - self.stop_loss)
        reward = abs(self.take_profit - self.price)
        return reward / risk if risk > 0 else None


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, name: str, parameters: dict[str, Any] | None = None) -> None:
        self.name = name
        self.parameters = parameters or {}
        self._min_bars = self.parameters.get("min_bars", 50)

    @property
    @abstractmethod
    def strategy_type(self) -> str:
        """Return strategy type (smc, rule_based, ml, hybrid)."""
        ...

    @abstractmethod
    def generate_signals(self, candles: list[Candle]) -> list[StrategySignal]:
        """
        Generate trading signals from OHLCV candles.

        Args:
            candles: List of candles in chronological order.

        Returns:
            List of StrategySignal objects.
        """
        ...

    def validate_candles(self, candles: list[Candle]) -> bool:
        """Validate that we have enough candles to run the strategy."""
        if len(candles) < self._min_bars:
            return False
        return True

    def _to_arrays(self, candles: list[Candle]) -> tuple[np.ndarray, ...]:
        """Convert candle list to numpy arrays."""
        opens = np.array([c.open for c in candles], dtype=np.float64)
        highs = np.array([c.high for c in candles], dtype=np.float64)
        lows = np.array([c.low for c in candles], dtype=np.float64)
        closes = np.array([c.close for c in candles], dtype=np.float64)
        volumes = np.array([c.volume for c in candles], dtype=np.float64)
        return opens, highs, lows, closes, volumes
